# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
<<<<<<< HEAD
# You can use `rails secret` to generate a secure secret key.
=======
# You can use `rake secret` to generate a secure secret key.
>>>>>>> 2905e72d927fd41518bb7ba52e3d68bf1ffabf98

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

<<<<<<< HEAD
# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbd634b9d8b6fe6ce7ca7c5a61dba8f9bbf3c6bf6c6af9637bb7d647e9f88633ae86f800df9e8bba02f2a0b2b6a15a9acdca16e855ff1cbd6e3fdcddea4b3512

test:
  secret_key_base: fdbb0621e317a7c8495d2ca8452fd57b070ca6877e0f0f70b8988c5fec9cc941e2bd167ff4392de924a956fc5bf79af9be2be3a159b338f284259b660de045bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

=======
development:
  secret_key_base: 7c9bc5388387114151569bd535716b0a1a42b7b79fa4ef7ed750f8e61b4161d454d9d82849563f9bf191b8be47e8cce42204658c5a609580d1ee20d43d0a3581

test:
  secret_key_base: e75b2d58e3c5d8a0e2dd4a477b1cde3353df9413e69190a5a115204413d3716ebb7dbab5b00c56f84f7b1a99f11e2fb7bb172509cdb2b99fab859ce38efd2a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
>>>>>>> 2905e72d927fd41518bb7ba52e3d68bf1ffabf98
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
